# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'natacha'

menu:
- {name: 'Portfolio', link: 'https://natachasochat.myportfolio.com/work'}
- {name: 'Natacha Net', link: 'http://www.natacha.net/'}
- {name: 'About', folder: 'pages', file: 'about'}
- {name: 'NKG Boston', link: 'http://www.natacha.net/NKGBoston2012/index.html'}
- {name: 'Contact', link: 'https://natachasochat.myportfolio.com/contact'}
- {name: 'wildDreamer Studio', link: 'https://wilddreamer-studio.business.site/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/WildNatacha'}
- {icon: 'facebook', link: 'https://www.facebook.com/natacha.sochat'}
- {icon: 'instagram', link: 'https://instagram.com/natachasochat'}
- {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'
post_date_prefix: 'Written on'
